
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Label fileLabel;
	private global::Gtk.Button openFileButton;
	private global::Gtk.Label outputLabel;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Sprite Sheet Analyzer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("File:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 16;
		w1.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.fileLabel = new global::Gtk.Label ();
		this.fileLabel.Name = "fileLabel";
		this.fileLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("(none)");
		this.fixed1.Add (this.fileLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileLabel]));
		w2.X = 64;
		w2.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.openFileButton = new global::Gtk.Button ();
		this.openFileButton.CanFocus = true;
		this.openFileButton.Name = "openFileButton";
		this.openFileButton.UseUnderline = true;
		this.openFileButton.Label = global::Mono.Unix.Catalog.GetString ("Open...");
		this.fixed1.Add (this.openFileButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.openFileButton]));
		w3.X = 8;
		w3.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.outputLabel = new global::Gtk.Label ();
		this.outputLabel.Name = "outputLabel";
		this.outputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("(output)");
		this.fixed1.Add (this.outputLabel);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.outputLabel]));
		w4.X = 16;
		w4.Y = 64;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openFileButton.Clicked += new global::System.EventHandler (this.openFileClicked);
	}
}
