
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Label fileLabel;
	private global::Gtk.Button openFileButton;
	private global::Gtk.Label outputLabel;
	private global::Gtk.RadioButton horizontalRadioButton;
	private global::Gtk.RadioButton islandsRadioButton;
	private global::Gtk.Button clipboardButton;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::SpriteSheetAnalyzer.IslandEditor islandeditor;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Sprite Sheet Analyzer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("File:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 16;
		w1.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.fileLabel = new global::Gtk.Label ();
		this.fileLabel.Name = "fileLabel";
		this.fileLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("(none)");
		this.fixed1.Add (this.fileLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.fileLabel]));
		w2.X = 64;
		w2.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.openFileButton = new global::Gtk.Button ();
		this.openFileButton.CanFocus = true;
		this.openFileButton.Name = "openFileButton";
		this.openFileButton.UseUnderline = true;
		this.openFileButton.Label = global::Mono.Unix.Catalog.GetString ("Open...");
		this.fixed1.Add (this.openFileButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.openFileButton]));
		w3.X = 8;
		w3.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.outputLabel = new global::Gtk.Label ();
		this.outputLabel.Name = "outputLabel";
		this.outputLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("(output)");
		this.fixed1.Add (this.outputLabel);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.outputLabel]));
		w4.X = 16;
		w4.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.horizontalRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Horizontal offset + width"));
		this.horizontalRadioButton.CanFocus = true;
		this.horizontalRadioButton.Name = "horizontalRadioButton";
		this.horizontalRadioButton.DrawIndicator = true;
		this.horizontalRadioButton.UseUnderline = true;
		this.horizontalRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.horizontalRadioButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.horizontalRadioButton]));
		w5.X = 150;
		w5.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.islandsRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Islands x,y,w,h"));
		this.islandsRadioButton.CanFocus = true;
		this.islandsRadioButton.Name = "islandsRadioButton";
		this.islandsRadioButton.DrawIndicator = true;
		this.islandsRadioButton.UseUnderline = true;
		this.islandsRadioButton.Group = this.horizontalRadioButton.Group;
		this.fixed1.Add (this.islandsRadioButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.islandsRadioButton]));
		w6.X = 150;
		w6.Y = 32;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.clipboardButton = new global::Gtk.Button ();
		this.clipboardButton.CanFocus = true;
		this.clipboardButton.Name = "clipboardButton";
		this.clipboardButton.UseUnderline = true;
		this.clipboardButton.Label = global::Mono.Unix.Catalog.GetString ("Copy to Clipboard");
		this.fixed1.Add (this.clipboardButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.clipboardButton]));
		w7.X = 350;
		w7.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 700;
		this.GtkScrolledWindow.HeightRequest = 300;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w8 = new global::Gtk.Viewport ();
		w8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.islandeditor = new global::SpriteSheetAnalyzer.IslandEditor ();
		this.islandeditor.WidthRequest = 700;
		this.islandeditor.HeightRequest = 300;
		this.islandeditor.Name = "islandeditor";
		w8.Add (this.islandeditor);
		this.GtkScrolledWindow.Add (w8);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w11.X = 262;
		w11.Y = 64;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 970;
		this.DefaultHeight = 414;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openFileButton.Clicked += new global::System.EventHandler (this.openFileClicked);
		this.horizontalRadioButton.Clicked += new global::System.EventHandler (this.horizontalClicked);
		this.islandsRadioButton.Clicked += new global::System.EventHandler (this.islandsClicked);
		this.clipboardButton.Clicked += new global::System.EventHandler (this.clipboardButtionClicked);
	}
}
